### ISSUE TITLE
OpenCV with Cuda

### ISSUE THREAD

**Issue by Byrdman32** [MissouriMRDT/Autonomy_Software#1]
When making the docker image that has OpenCV installed we were having issues where it would crash anytime we tried to install it with CUDA. At some point we should get this working so that we are getting the best performance.

> _Note: We can still use ArUco without CUDA but we will be stuck having it run on the CPU only and will be missing out of the performance boosts from using the onboard GPU_

**Comment by ClayJay3** [comment]
Ubuntu Dockerfile has been updated to successfully build OpenCV with CUDA, still working on Jetson Dockerfile. In order to actually use the GPU on the host machine through the container, we will likely need to make some changes to the .devcontainer file to enable GPU passthrough.
