### ISSUE TITLE
Implement GPS fusion

### ISSUE THREAD

**Issue by ClayJay3** [MissouriMRDT/Autonomy_Software#124]
GPS Fusion is a feature of the ZEDSDK library and is only available for certain ZED Cameras. Last year, we only realigned the relative position of the camera to our GPS's absolute position when the rover was stationary and the accuracy of the GPS was good enough.

Using the GPS Fusion feature will let the ZEDSDK do all the work for us by continuously using the relative tracking and GPS input to sort of "dead reckon" the most accurate position of the camera/rover. This will give us both enhanced accuracy and optimal refresh rates for rover odometry.

**Comment by Byrdman32** [comment]
Moved to [Sprint 2a](https://github.com/MissouriMRDT/Autonomy_Software/milestone/6) because of more pressing issues needing to be completed in [Sprint 1](https://github.com/MissouriMRDT/Autonomy_Software/milestone/3).
