### ISSUE TITLE
Implement Feature Rich ASTAR Pathfinder

### ISSUE THREAD

**Issue by ClayJay3** [MissouriMRDT/Autonomy_Software#144]
# Path Planning Namespace

### Objective

The pathplanning namespace introduces an ASTAR class implementing the A* algorithm, enhanced with object avoidance capabilities. The class seamlessly navigates around objects during path planning.

### ASTAR Class

- The ASTAR class is the core component.
- It integrates the standard A* algorithm, but also incorporates object avoidance logic for dynamic path planning.

## Object Representation

- Objects within the namespace have:
  - Location (should be stored using [geoops::UTMCoordinate](https://missourimrdt.github.io/Autonomy_Software/structgeoops_1_1UTMCoordinate.html))
  - Radius defining their spatial extent.

### Class Structure

- The namespace `pathplanner` currently centers around the ASTAR class, but should be designed so that new algorithms can be added in the future.
- The class seamlessly merges A* algorithm logic with object avoidance, by automatically generating a path around the current obstacle data stored within the class.

### Object Integration

- Method: `AddObject(center, radius)` to include objects in the planner. I might be useful to define a struct `ASTARObject` specifically for storing this data.
- Objects alter the planner's path calculation based on their spatial characteristics.

### Path Planning Algorithm

- A* algorithm computes the optimal path considering object locations.
- The planner adjusts its route to circumvent objects efficiently.

**Comment by ClayJay3** [comment]
@RyanW83 What's the status of this? Do you think you could get this class written before January 20, 2024 when [Sprint2b](https://github.com/MissouriMRDT/Autonomy_Software/milestone/4) closes?

**Comment by Byrdman32** [comment]
Re-opening this issue as it is linked to PR #259.
