### ISSUE TITLE
Lidar support

### ISSUE THREAD

**Issue by omc8db** [MissouriMRDT/Autonomy_Software#25]

**Comment by sdlouhy** [comment]
[this is a google doc on how to get our LiDAR system to work](https://docs.google.com/document/d/1CRF0vxlihf06AxhST3poyUCXbA1bQxFRsFHC34DPvaM/edit)

**Comment by sdlouhy** [comment]
Made comparison sheet for current system and the [Scanse Sweep](https://docs.google.com/document/d/1amMt2I6R9oMEwnjlP0y9w9KKk-kGYEAsZlu5HSybd_U/edit)

**Comment by sdlouhy** [comment]
lidar currently can detect data without actuating.  waiting on the board to implement that.
