### ISSUE TITLE
Implement Multi-Threading into the Codebase

### ISSUE THREAD

**Issue by ClayJay3** [MissouriMRDT/Autonomy_Software#29]
Before we can begin most of our development for Autonomy C++, we need to implement and effective multi-threading system to make sure we are running as efficient as possible.

Look into boost::threads

**Comment by ClayJay3** [comment]
Basic threading with the AutonomyThread base class has been implemented. It is structured so that all of the threaded code will be placed in a pure virtual method that the user must define. The code within that function will run forever until the Stop() method is called from either inside or outside of the thread. Then, once the thread is finished with code execution, call the Join() method to close the thread.

**Comment by Byrdman32** [comment]
> Basic threading with the AutonomyThread base class has been implemented. It is structured so that all of the threaded code will be placed in a pure virtual method that the user must define. The code within that function will run forever until the Stop() method is called from either inside or outside of the thread. Then, once the thread is finished with code execution, call the Join() method to close the thread.

@ClayJay3 I would make sure this is documented somewhere in the docs page since this will eventually be closed.

**Comment by ClayJay3** [comment]
I'll add a formal page to the docs before the threading branch is merged, I'm moreso just journaling here.
