### ISSUE TITLE
[Bug] Increase Codebase Unit Test Coverage

### ISSUE THREAD

**Issue by Kai-Shafe** [MissouriMRDT/Autonomy_Software#342]
### Description

Write unit tests for under represented areas of the codebase.

### Steps to Reproduce

Run Code Coverage Report

### Expected Behavior

At least 75% Code Coverage

### Actual Behavior

Code Coverage is at 26.25%

### Environment

Jammy, JetPack

### Version

v25.1.0

### Additional Context

https://app.codecov.io/gh/MissouriMRDT/Autonomy_Software

**Comment by ClayJay3** [comment]
I added some tests for the PIDController class since I wrote that class originally and didn't do a good job of covering everything.
