### ISSUE TITLE
Compare logging methods and implement an optimal method

### ISSUE THREAD

**Issue by Byrdman32** [MissouriMRDT/Autonomy_Software#7]
Having a easy to use logging implementation will be vital to debugging and having log history.

Libraries to look at:
- **plog:** https://github.com/SergiusTheBest/plog (Currently Implemented)
- **fmtlog:** https://github.com/MengRao/fmtlog
- **clutchlog:** https://github.com/nojhan/clutchlog
- **spdlog:** https://github.com/gabime/spdlog
- **loguru:** https://github.com/emilk/loguru
- **glog:** https://github.com/google/glog
- **boost.log:** https://github.com/boostorg/log
- **quill:** https://github.com/odygrd/quill

**Comment by ClayJay3** [comment]
Some more c++ logging tools I found:
https://github.com/nojhan/clutchlog (very nice formatting, colors, and stack trace/file locations but slow and seems to be poorly implemented)

https://github.com/gabime/spdlog (prioritizes extreme speed)

https://github.com/emilk/loguru (relatively fast and kinda pretty)

**Comment by Byrdman32** [comment]
plog is working fine and will be fine for now. Potential project for the future.

**Comment by Byrdman32** [comment]
Issues with plog not being included. Beginning transition to spdlog.

**Comment by Byrdman32** [comment]
Switching to quill
