### ISSUE TITLE
Utah Terrain Mapping?

### ISSUE THREAD

**Issue by Byrdman32** [MissouriMRDT/Autonomy_Software#80]

**Comment by ClayJay3** [comment]
I'd like to eventually work on this, no promises. Might unassign myself later...

**Comment by ClayJay3** [comment]
Currently works with the ZED spatial mapping, will continue to implement and optimize it as other code starts to get written for the codebase. Will probably be part of the CameraHandler.

**Comment by Byrdman32** [comment]
I haven't added much detail about this issue yet but I was looking at making use of LiDAR Data from the USGS to have a terrain model within the software that can be used during path finding. However, I do like the idea of real time data as well.

A description of the project will be added to the issue soon.

**Comment by ClayJay3** [comment]
This works now works. A spatial map is automatically generated from the ZED camera and saved to the log directory upon a clean exit.
